import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await context.dispose();

	// Second bundle: the fetch-title CLI for use outside Obsidian (plain Node).
	// "obsidian" is aliased to a local stub - the CLI always injects a fetch-based
	// request executor, so the aliased symbols never run; this just satisfies the
	// bundler for plugin modules reachable from fetchTitle().
	const cliContext = await esbuild.context({
		entryPoints: ["src/cli/fetchTitleCli.ts"],
		bundle: true,
		platform: "node",
		format: "cjs",
		target: "es2022",
		alias: {
			obsidian: "./src/cli/obsidian-stub.ts",
		},
		logLevel: "info",
		sourcemap: false,
		treeShaking: true,
		outfile: "dist/fetch-title.cjs",
	});
	await cliContext.rebuild();
	await cliContext.dispose();

	process.exit(0);
} else {
	await context.watch();
}
